[package]
name = "AdventOfCode"
version = "0.1.0"
edition = "2021"

[dependencies]
petgraph = "0.6.5"
regex = "*"
ndarray = "0.14"
ndarray-linalg = { version = "0.13", features = ["openblas-static"] }
num-bigint = "*"